#!/usr/bin/env bash
set -x
set -eo pipefail

# Install Conda
tgt="/opt/romancal"
platform="$(uname -s)"
arch="$(uname -m)"
url="https://github.com/conda-forge/miniforge/releases/latest/download"
fn="Mambaforge-${platform}-${arch}.sh"
url="$url/${fn}"

curl -LO "${url}"

romancal_path="/opt/romancal"
bash ./${fn} -u -b -p $tgt
PATH=$PATH:$romancal_path/bin
export PATH

MAMBA_NO_BANNER=1
export MAMBA_NO_BANNER

mamba update -y conda
mamba env create --name romancal --file /tmp/build/romancal-env.yml
